- name: install httpd package (CentOS)
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
 
- name: start and enable httpd (CentOS)
  tags: apache,centos,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
 
- name: install apache2 package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"
 
- name: change index.html
  tags: index,ubuntu
  lineinfile:
    path: /var/www/html/index.html
    regexp: '^    <p>'
    line: '    <p>Ansible is awesome! xDD</p>'
  when: ansible_distribution == "Ubuntu"
  register: apache2
 
- name: restart apache2 (Ubuntu)
  tags: apache, ubuntu
  service:
    name: apache2
    state: restarted
  when: apache2.changed   
 
- name: copy html file for site
  tags: apache,apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644