- name: install web server packages
  tags: apache,apache2,centos,httpd,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest
 
- name: start and enable apache service
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
 
 
- name: change index.html
  tags: index,ubuntu
  lineinfile:
    path: /var/www/html/index.html
    regexp: '^    <p>'
    line: '    <p>Ansible is awesome! xDDD</p>'
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache
 
# - name: copy html file for site
#   tags: apache,apache,apache2,httpd
#   copy:
#     src: default_site.html
#     dest: /var/www/html/index.html
#     owner: root
#     group: root
#     mode: 0644